"""add_task_history

Revision ID: 0004_add_task_history
Revises: 0003_convert_ids_to_uuid
Create Date: 2026-05-11 18:14:53.298459
"""
from alembic import op
import sqlalchemy as sa


revision = '0004_add_task_history'
down_revision = '0003_convert_ids_to_uuid'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_history_task_created', 'task_history', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_history_user_id'), 'task_history', ['user_id'], unique=False)
    op.create_table('task_history_fields',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('history_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['task_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_history_fields_history_id'), 'task_history_fields', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_fields_history_id'), table_name='task_history_fields')
    op.drop_table('task_history_fields')
    op.drop_index(op.f('ix_task_history_user_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index('ix_task_history_task_created', table_name='task_history')
    op.drop_table('task_history')
    # ### end Alembic commands ###
